### ISSUE TITLE
[Feature Request]: Output Validation

### ISSUE THREAD

**Issue by alckasoc** [agential-ai/agential#22]
### Feature Description

Need some way to standardize/guarantee model outputs come in certain formats. 

- https://github.com/guidance-ai/guidance
- https://www.guardrailsai.com/
- https://www.rebuff.ai/
- https://github.com/jxnl/instructor

**Comment by Tsomoriri** [comment]
I can start working on integrating rails from guardrails package. let  the user specify  rails for a trajectory which will act as boundary conditions for the llm output. 
The pydantic can be used to tailor the thinking process even better.
