### ISSUE TITLE
[Feature Request]: GSM8k for CRITIC

### ISSUE THREAD

**Issue by alckasoc** [agential-ai/agential#73]
### Feature Description

Familiarize yourself with the repository and take a look the CRITIC [repo](https://github.com/microsoft/ProphetNet/tree/master/CRITIC), [paper](https://arxiv.org/abs/2305.11738), and [GSM8k](https://arxiv.org/abs/2110.14168).

There are 3 math reasoning tasks tested in the paper: GSM8k, SVAMP, TabMWP. 

Currently, the CRITIC implementation only has [prompts](https://github.com/alckasoc/agential/blob/main/agential/cog/prompts/critic.py) for HotpotQA and TriviaQA.

Add the GSM8k prompts and relevant logic to the current CRITIC implementation. You'll see that an agent's current structure is divided into `cog/agent`, `cog/modules`, and `cog/functional/`. This task will require you to make modifications in `cog/prompts`, but will also require you to test your code in all the other relevant modules `cog/functional` and `cog/agent`. CRITIC does not have any `cog/modules`. 

**What to submit**:

- [ ] Set up your environment via the CONTRIBUTING.md
- [ ] Make a Pull Request (PR)
- [ ] Add the prompts for GSM8k
- [ ] Write a short notebook `tmp.ipynb` in `cog/agent` showcasing the agent ran on a sample question from the benchmark
  - [ ] Add print statements for all calls to the LLM for easier debugging + I can easily verify the outputs
- [ ] Request a review from @alckasoc 

_If there is any additional logic for how CRITIC is tested on GSM8k (refer to the paper's [repo](https://github.com/microsoft/ProphetNet/tree/master/CRITIC)), include these specifications in the PR description._

Feel free to ask me questions on slack if you're confused! Good luck!

deadline: 5 2 2024

**Comment by berniewu2** [comment]
i'm bernie

**Comment by emmalin-7** [comment]
ill take this issue
